repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
   - id: trailing-whitespace
   - id: end-of-file-fixer
   - id: check-yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.2.1
  hooks:
   - id: ruff
     args: [ --fix ]
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.34.1
  hooks:
   - id: djlint-reformat-django
   - id: djlint-django
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.2.1
  hooks:
    - id: ruff-format
